name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: ls -a
      - name: Run Tests
        run: npm run test