name: Deploy to Amazon ECS

on:
  push:
    branches:
      - prod
jobs:
  initialize:
    name: Info
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: npm -V
      - name: docker
        run: docker --version